### ISSUE TITLE
can't change tmp folder for Hadoop

### ISSUE THREAD

**Issue by xuchen** [joshua-decoder/joshua#131]
the pipeline doc says:

Hadoop uses a lot (use --tmp /path/to/tmp to specify an alternate place for temporary data; we suggest you use a local disk partition with tens or hundreds of gigabytes free

However, passing "--tmp" doesn't change Hadoop's default tmp folder, nor does changing the "hadoop.tmp.dir" option in  joshua-v5.0/scripts/training/templates/hadoop/core-site.xml

I used joshua v5.0 on a standard linux desktop.

**Comment by mjpost** [comment]
With pre-existing Hadoop installations, changing this is beyond the reach of the pipeline.

Hadoop will now be unpacked to `$TMPDIR` with Joshua 6.0.3.
