### ISSUE TITLE
Solved the problem of thrax exception occuring due to no space left problem.

### ISSUE THREAD

**Issue by bibekiit** [joshua-decoder/joshua#152]
I can suggest this way to change the directory: Assuming you want it to write to directory YOUR_BASE_DIR in a partition with sufficient memory.
Create/edit this configuration xml file in your working directory:

Change ./working/hadoop-0.20.2/conf/mapred-site.xml

<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

<configuration>
    <property>
        <name>hadoop.tmp.dir</name>
        <value><YOUR_BASE_DIR>/mapred/tmp</value>
    </property>

    <property>
        <name>mapred.local.dir</name>
        <value><YOUR_BASE_DIR>/mapred/local(Add multiple folders by comma separating the folders- This is the most busy place in the mapred folder so might need several folders)</value>
        <final>true</final>
    </property>

    <property>
        <name>mapred.system.dir</name>
        <value><YOUR_BASE_DIR>/mapred/system</value>
        <final>true</final>
    </property>
</configuration>

Then rerun your experiment.
When it is running, you can issue the command "ls <YOUR_BASE_DIR>/mapred" to verify whether it is writing to that folder as you expected.

**Comment by mjpost** [comment]
Hi,

I believe I fixed this in commit 9c4a64744cc9c1fcb4b999a27e4aeaf9a3d2f38c, which will soon be pushed to master. 

Sorry for the delay :)

matt
