### ISSUE TITLE
Fix ivy

### ISSUE THREAD

**Issue by mjpost** [joshua-decoder/joshua#190]
Ivy should not have to check all its downloads every time.

Also, ivy shouldn't fail if there is no internet connection. This prevents builds!

Would like ivy to download the first time, and then know it's done so, not running any more for later runs (and not killing builds when there is no internet connection).

**Comment by lukeorland** [comment]
This may be just a matter of updating Ivy to version 2.0+. I see a new option:

> Attribute: refresh
> Description: true to force Ivy to resolve dynamic revision in this resolve process, false to use cached resolved revision since 2.0
> Required: No. defaults to false

http://ant.apache.org/ivy/history/2.3.0/use/resolve.html

**Comment by lukeorland** [comment]
@mjpost Please give the `ivy-less-downloads` branch a try from my `git@github.com:lukeorland/joshua.git` repo. I'll try it out on a vagrant box without internet.

**Comment by mjpost** [comment]
I tried it and I think it looks good, pulling in.
