### ISSUE TITLE
Certain strings cause the decoder server to shutdown with an exception

### ISSUE THREAD

**Issue by tpanningnextcen** [joshua-decoder/joshua#193]
While translating a bunch of strings, I ran into a couple character combinations that cause the decoder server to crash. If these are reserved sequences or command sequences, can there be a documentation page that lists them? Also, can the server be modified so that it doesn't shutdown on an exception?

Open and/or close square brackets: for example, the string "[]" will generate the following output:
```
Input 3: <s> [] </s>
Input 3: Collecting options took 0.000 seconds
* Decoder: fatal uncaught runtime exception on sentence 3: Index: 297138, Size: 1
java.lang.IndexOutOfBoundsException: Index: 297138, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at joshua.decoder.ff.lm.StateMinimizingLanguageModel.compute(StateMinimizingLanguageModel.java:111)
	at joshua.decoder.chart_parser.ComputeNodeResult.<init>(ComputeNodeResult.java:88)
	at joshua.decoder.phrase.EdgeGenerator.addCandidate(EdgeGenerator.java:67)
	at joshua.decoder.phrase.Stacks.search(Stacks.java:146)
	at joshua.decoder.DecoderThread.translate(DecoderThread.java:113)
	at joshua.decoder.Decoder$DecoderThreadRunner.run(Decoder.java:225)
```

Three open parenthesis: for example, the string "(((":
```
Input 1: <s>  </s>
Input 1: Collecting options took 0.000 seconds
Input 1: Search took 0.001 seconds
Input 1: Translation took 0.001 seconds
Memory used after sentence 1 is 661.5 MB
* Decoder: fatal uncaught runtime exception on sentence 1: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1911)
	at joshua.decoder.Translation.<init>(Translation.java:53)
	at joshua.decoder.DecoderThread.translate(DecoderThread.java:136)
	at joshua.decoder.Decoder$DecoderThreadRunner.run(Decoder.java:225)
```

**Comment by mjpost** [comment]
Yes, both of these sequences are special markers. Three leading parens is used to denote lattice input, and square brackets mark nonterminals.

Are you using a prepackaged model / language pack? There is a script prepare.sh that will escape these characters prior to passing them to Joshua.

**Comment by tpanningnextcen** [comment]
I'm using the Arabic language pack, and connecting to the server that opens on port 5674. Unfortunately, both of these character sequences (and the triple pipe (|||)) appear in my source documents... apparently people say the darnedest things on Twitter.

The most troublesome part is that the server shuts down with these inputs. If it could catch the exception and just return the provided string (since that's what it does in other cases when it can't translate a string), that would be much preferable.

**Comment by mjpost** [comment]
Sure, I understand. I agree that it should not shut down on an error like this and will get to that.

If you run your input through the prepare.sh script before sending it to the server (I believe this is described in the README), however, it will solve this problem for you, without affecting the translations at all.

**Comment by tpanningnextcen** [comment]
I didn't notice that the README in the distribution is different from the README on the github site. Now I see how to run it, thanks.

**Comment by mjpost** [comment]
Hi — what github README are you referring to?

**Comment by tpanningnextcen** [comment]
The one that is shown when you go to the main page for this repository: https://github.com/joshua-decoder/joshua (which is also the page linked to from the joshua-decoder.org site). That page doesn't mention the prepare.sh script.

**Comment by mjpost** [comment]
Okay, I see. Yes, only the language-pack specific READMEs discuss how to use the language packs. Sorry for the confusion.

**Comment by mjpost** [comment]
Can you confirm that running your data through the `prepare.sh` script solves your problems?
