### ISSUE TITLE
Homebrew formulae for Joshua

### ISSUE THREAD

**Issue by lewismc** [joshua-decoder/joshua#195]
I said a while back I would work on a Homebrew package for Joshua. This ticket is an attempt to honor that so I will make an effort to hack this one out.

**Comment by mjpost** [comment]
Sounds great!

**Comment by lewismc** [comment]
Began working this afternoon. Will hopefully finish tomorrow Matt. Will
update here ASAP.

On Sunday, May 10, 2015, Matt Post <notifications@github.com> wrote:

> Sounds great!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshua-decoder/joshua/issues/195#issuecomment-100748567>
> .
>


-- 
*Lewis*

**Comment by chrismattmann** [comment]
@lewismc do you have something I can work from here?

**Comment by lewismc** [comment]
Yep I do, the PR is not for Joshua it is for home brew
I'll send what I have shortly...

On Friday, June 19, 2015, Chris Mattmann <notifications@github.com> wrote:

> @lewismc <https://github.com/lewismc> do you have something I can work
> from here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshua-decoder/joshua/issues/195#issuecomment-113536718>
> .
>


-- 
*Lewis*

**Comment by chrismattmann** [comment]
cool, thanks.

**Comment by lewismc** [comment]
Took me way to long but this is now nearly off of my TODO list.
https://github.com/Homebrew/homebrew/pull/44371
Sorry about the wait folks. The formula will work with a number of options namely;
```
lmcgibbn@LMC-032857 /usr/local(joshua) $ brew options joshua-v
--with-ar-en-phrase-pack
	Build with Arabic–English phrase-based model [2.4 GB], built from the LDC Arabic-Dialect/English parallel text, the ISI Arabic–English automatically extracted parallel text, and translations of the Arabic CALLHOME transcripts, and with an English Gigaword language model.
--with-es-en-phrase-pack
	Build with Spanish–English phrase-based model [1.9 GB], built on Europarl and the Fisher and CALLHOME parallel dataset.
--with-language-packs
	Build with all available community language packs (es-->en and ar-->en)
--HEAD
	Install HEAD version
``` 
The package is called joshua-v due to the published artifact being called joshua-v${release.number}.tar.gz. This is outwith my control.

**Comment by mjpost** [comment]
This looks great, though too bad about the name.

How hard is this to update when new versions of Joshua come out? 6.0.5 will be out soon with a number of speed improvements and bug fixes.

**Comment by lewismc** [comment]
Hi Matt,
If you can change the .tar.gz to 6.0.5.tar.gz instead of v6.0.5.
If you can do this then it will be automatic as I'll update the formula to
resolve to the new correct tar.gz file.
I'll update here once the Formula has been merged.
Thanks

On Tue, Sep 29, 2015 at 2:48 PM, Matt Post <notifications@github.com> wrote:

> This looks great, though too bad about the name.
>
> How hard is this to update when new versions of Joshua come out? 6.0.5
> will be out soon with a number of speed improvements and bug fixes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshua-decoder/joshua/issues/195#issuecomment-144169016>
> .
>



-- 
*Lewis*

**Comment by lewismc** [comment]
New PR here
https://github.com/Homebrew/homebrew/pull/44490
A number of issues were logged and discovered whilst building the brew formula so hopefully we can iron some of them out.

**Comment by lewismc** [comment]
Hi @mjpost can you please stage https://github.com/joshua-decoder/indian-parallel-corpora/tarball/master as a static indian-languages.tgz artifact somewhere?
When I download it from Github within the homebrew formula it unpacks to a different directory every time. The brew recipe requires static files with a consistent sha256. Right now this is impossible for me to do unless the artifact is staged. Can you name it indian-languages-6.0.4.tgz ?

**Comment by mjpost** [comment]
I just created an official release. You can [download using this link](https://github.com/joshua-decoder/indian-parallel-corpora/archive/1.0.tar.gz). I will update the quick start instructions.

**Comment by lewismc** [comment]
Grand. Nearly ready for iteration 4. Will be posting in around 10 minutes for the PR.

**Comment by lewismc** [comment]
PR updated on and will hopefully be merged this time.
https://github.com/Homebrew/homebrew/pull/44490
Fingers crossed.

**Comment by mjpost** [comment]
Hi Lewis — Sorry, just buried under other stuff. I hope to get to this today.

- matt

**Comment by lewismc** [comment]
No problems I'll update once the PR has been merged over at Homebrew.
Thanks

On Monday, October 5, 2015, Matt Post <notifications@github.com> wrote:

> Hi Lewis — Sorry, just buried under other stuff. I hope to get to this
> today.
>
>    - matt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshua-decoder/joshua/issues/195#issuecomment-145503164>
> .
>


-- 
*Lewis*

**Comment by lewismc** [comment]
OK this issue has been addressed and Joshua is available in Homebrew :)
You can check out the options as follows
```
lmcgibbn@LMC-032857 /usr/local(joshua) $ brew info joshua
joshua: stable 6.0.5, HEAD
Statistical machine translation decoder.
http://joshua-decoder.org/
/usr/local/Cellar/joshua/6.0.5 (1855 files, 172M) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/joshua.rb
==> Dependencies
Build: ant ✔, boost ✔, md5sha1sum ✔
==> Options
--with-ar-en-phrase-pack
	Build with Arabic–English phrase-based model [2.4 GB].
--with-es-en-phrase-pack
	Build with Spanish–English phrase-based model [1.9 GB].
--HEAD
	Install HEAD version
```

**Comment by lewismc** [comment]
@mjpost can we update the Homebrew formula within the release procedure? It would be nice to have it up-to-date.

**Comment by mjpost** [comment]
Yes, of course. What needs to be done?

**Comment by lewismc** [comment]
So if you look at the [Joshua recipe](https://github.com/Homebrew/homebrew/blob/b853e4a9463fb775e76301222598375c35a01aef/Library/Formula/joshua.rb) all you need to do is
1.  update the [link to the Joshua release artifact](https://github.com/Homebrew/homebrew/blob/b853e4a9463fb775e76301222598375c35a01aef/Library/Formula/joshua.rb#L4)
2. update the [SHA256 signature](https://github.com/Homebrew/homebrew/blob/b853e4a9463fb775e76301222598375c35a01aef/Library/Formula/joshua.rb#L5) for the release artifact

... that's it. Super simple :)

**Comment by mjpost** [comment]
Update it to what? It looks up-to-date to me.

**Comment by lewismc** [comment]
Sorry, I meant that when a new release is made then both of the above can be updated to the new release artifact. Is there a release process somewhere that I can see? If not then maybe now is a good time to make one and I can add the Homebrew portion. wdyt?

**Comment by mjpost** [comment]
There is no release document, but there should be. I've added [a TODO item](https://github.com/joshua-decoder/joshua-decoder.github.com/issues/4).
