### ISSUE TITLE
Contributors page doesn't include people who have Github contributions

### ISSUE THREAD

**Issue by chrismattmann** [joshua-decoder/joshua#206]
I and some others (e.g., Lewis John McGibbney) have made some Github contributions to Joshua but aren't listed on the contributors page:

http://joshua-decoder.org/contributors.html

Is this page managed in Git? Can I submit a pull request to update it?

**Comment by chrismattmann** [comment]
cc @lewismc

**Comment by lewismc** [comment]
Bewm

On Friday, June 19, 2015, Chris Mattmann <notifications@github.com> wrote:

> cc @lewismc <https://github.com/lewismc>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshua-decoder/joshua/issues/206#issuecomment-113536582>
> .
>


-- 
*Lewis*

**Comment by mjpost** [comment]
It is, but I'll just fix it (unless you prefer a PR!)

https://github.com/joshua-decoder/joshua-decoder.github.com

**Comment by chrismattmann** [comment]
thanks @mjpost I'll at least add @lewismc and me, and maybe you can take from there? Thx.

**Comment by chrismattmann** [comment]
thanks this is done.
