### ISSUE TITLE
Java 8 breaks test cases

### ISSUE THREAD

**Issue by mjpost** [joshua-decoder/joshua#224]
The regression test cases ("ant -f $JOSHUA/build.xml test") should pass. Currently Java 8 seems to break them. In particular, the k-best extraction test hangs indefinitely:

    cd $JOSHUA/test/decoder/k-best-extraction
    ./test.sh

(hangs forever, or at least for minutes and minutes, at 100% CPU).

This works perfectly when doing a simple recompile with Java 7.

**Comment by mjpost** [comment]
One update: limiting the n-best output helps in some cases:

    cd $JOSHUA/test/decoder/k-best-extraction
    cat input.txt | $JOSHUA/bin/joshua-decoder -c joshua.config -top-n 100

exits pretty quickly. It looks like Java 8 has introduced some sort of exponential increase on k-best extraction.

    for num in 100 200 300 400 500 600 700 800 900 1000; do
        cat input.txt | $JOSHUA/bin/joshua-decoder -m 8g -c joshua.config -top-n $num 2>&1 | grep extraction
    done

produces:

    Input 0: 100-best extraction took 0.431 seconds
    Input 0: 200-best extraction took 1.337 seconds
    Input 0: 300-best extraction took 2.798 seconds
    Input 0: 400-best extraction took 5.184 seconds
    Input 0: 500-best extraction took 12.190 seconds
    Input 0: 600-best extraction took 20.880 seconds
    Input 0: 700-best extraction took 50.407 seconds
    [killed]

Recompiling with Java 7 gives:

    Input 0: 100-best extraction took 0.932 seconds
    Input 0: 200-best extraction took 1.337 seconds
    Input 0: 300-best extraction took 1.646 seconds
    Input 0: 400-best extraction took 1.928 seconds
    Input 0: 500-best extraction took 1.977 seconds
    Input 0: 600-best extraction took 1.701 seconds
    Input 0: 700-best extraction took 1.754 seconds
    Input 0: 800-best extraction took 1.681 seconds
    Input 0: 900-best extraction took 2.039 seconds
    Input 0: 1000-best extraction took 2.120 seconds

This is pretty bad for a simple recompile!

cc: @fhieber

**Comment by jganitkevitch** [comment]
To me this looks like Java 7 was implicitly clearing some buffer which now
retains its contents. So we end up processing and ever-growing batch of
elements. Could that be the case somewhere?

**Comment by mjpost** [comment]
Nothing comes to mind. The other strange thing is that all the outputs come at once, even though we call out.flush() after each k-best item. This suggest all the work is being done in the KBestExtractor() constructor, but nothing happens there.

The k-best code is called in joshua.decoder.Translation.java (constructor).

**Comment by fhieber** [comment]
Very interesting data point. We have used Joshua extensively under java 8 with no obvious problems but have also observed very slow nbest decoding during tuning (nbest extraction times comparable or more of what you report here).
Furthermore, we have never used the existing test suite since these have failed, confirming your issue here. 

I will take a look at it asap.

**Comment by KellenSunderland** [comment]
Hello, Felix and I took a look a the code today and did some profiling to see if we could isolate any obvious problems.  So fare it's been with fairly limited success.  

The first thing we notice when profiling is that the hottest method is ''joshua.decoder.hypergraph.KBestExtractor$HypothesisExtractor.before()".  Within this, regex matching, but if you let the process run for a while and do some follow up profiling even priority queue and hash map operations are expensive.  

Later in execution "joshua.decoder.hypergraph.KBestExtractor$VirtualNode.lazyNext()" becomes the hottest method.

So no obvious hints towards what would cause the performance regression.  It seems that work is being fairly well distributed but we're possible doing a much larger search than we intend, or we're not being as lazy as we intend.  Felix + I will continue investigating on our end, but if anyone else has ideas feel free to chime in.  

![joshua perf 1](https://cloud.githubusercontent.com/assets/7443219/10581662/3442906c-7684-11e5-9290-c8d4c4a139f7.png)

![joshua perf 2](https://cloud.githubusercontent.com/assets/7443219/10581628/0a959e8a-7684-11e5-8691-c769c047c14c.png)

**Comment by mjpost** [comment]
Nothing comes to mind, unfortunately. I can take a look myself, but not until early November.

In the meantime, do you want to downgrade [your pull request](https://github.com/joshua-decoder/joshua/pull/214) to Java 7? If you can do that, I'll include it in the 6.0.5 release, which I plan to pull together in the next few days.

**Comment by mjpost** [comment]
(Also, I wonder if this is the kind of thing the Java folks should know about. It seems like a pretty serious bug that a straight recompile results in an exponential blowup of code runtime).

**Comment by fhieber** [comment]
maybe some internal changes in the regex engine from java 7 to java 8? Is there a specific reason why the HypothesisExtractor is working on a String level instead of merging int[] arrays when combining rules/derivations?

**Comment by mjpost** [comment]
Yes, it seems like this could be replaced to use arrays instead of strings and be much more efficient. It might get expensive to schlep all those arrays around, but it can't be worse than the current regex approach, and I agree that the implementation could be improved a lot.

I wonder if Java 7 precompiled the regex in the background once and then cached it, and maybe Java 8 is not doing that? That could explain the problem. In any case, using regex's here is definitely the wrong choice — I probably just did it this way because it was quick and didn't take too long.

**Comment by KellenSunderland** [comment]
I'm cautiously optimistic that I know what's going on here.  We might have a patch for you tomorrow to resolve this.  Looks like an issue with Java 8's HashMap switching to an underlying red / black tree after a certain number of items per bucket.

**Comment by mjpost** [comment]
Fixed with commit b2b9477b76e261927703bdd616d9d69f4a0d53f0
