### ISSUE TITLE
Problem building kenlm

### ISSUE THREAD

**Issue by sidhantsetia** [joshua-decoder/joshua#225]
@chrismattmann 
I've been trying to build Joshua Decoder but kenlm is giving errors while building. I'm trying to build on ubuntu 14.04 from the Master Branch.

This is the log that I get:
kenlm:
     kenlm:
     [exec] -- The C compiler identification is GNU 4.9.1
     [exec] -- The CXX compiler identification is GNU 4.9.1
     [exec] -- Check for working C compiler: /usr/bin/cc
     [exec] -- Check for working C compiler: /usr/bin/cc -- works
     [exec] -- Detecting C compiler ABI info
     [exec] -- Detecting C compiler ABI info - done
     [exec] -- Detecting C compile features
     [exec] -- Detecting C compile features - done
     [exec] -- Check for working CXX compiler: /usr/bin/g++
     [exec] -- Check for working CXX compiler: /usr/bin/g++ -- works
     [exec] -- Detecting CXX compiler ABI info
     [exec] -- Detecting CXX compiler ABI info - done
     [exec] -- Detecting CXX compile features
     [exec] -- Detecting CXX compile features - done
     [exec] -- Boost version: 1.59.0
     [exec] -- Found the following Boost libraries:
     [exec] --   program_options
     [exec] --   system
     [exec] --   thread
     [exec] --   unit_test_framework
     [exec] -- Configuring done
     [exec] -- Generating done
     [exec] -- Build files have been written to: /home/ssetia/dr/joshua/src/kenlm/build
     [exec] Scanning dependencies of target kenlm_util
     [exec] [  1%] Building CXX object util/CMakeFiles/kenlm_util.dir/double-conversion/bignum-dtoa.cc.o
     [exec] [  2%] Building CXX object util/CMakeFiles/kenlm_util.dir/double-conversion/bignum.cc.o
     [exec] [  3%] Building CXX object util/CMakeFiles/kenlm_util.dir/double-conversion/cached-powers.cc.o
     [exec] [  5%] Building CXX object util/CMakeFiles/kenlm_util.dir/double-conversion/diy-fp.cc.o
     [exec] [  6%] Building CXX object util/CMakeFiles/kenlm_util.dir/double-conversion/double-conversion.cc.o
     [exec] [  7%] Building CXX object util/CMakeFiles/kenlm_util.dir/double-conversion/fast-dtoa.cc.o
     [exec] [  8%] Building CXX object util/CMakeFiles/kenlm_util.dir/double-conversion/fixed-dtoa.cc.o
     [exec] [ 10%] Building CXX object util/CMakeFiles/kenlm_util.dir/double-conversion/strtod.cc.o
     [exec] [ 11%] Building CXX object util/CMakeFiles/kenlm_util.dir/stream/chain.cc.o
     [exec] [ 12%] Building CXX object util/CMakeFiles/kenlm_util.dir/stream/io.cc.o
     [exec] [ 14%] Building CXX object util/CMakeFiles/kenlm_util.dir/stream/line_input.cc.o
     [exec] [ 15%] Building CXX object util/CMakeFiles/kenlm_util.dir/stream/multi_progress.cc.o
     [exec] [ 16%] Building CXX object util/CMakeFiles/kenlm_util.dir/stream/rewindable_stream.cc.o
     [exec] [ 17%] Building CXX object util/CMakeFiles/kenlm_util.dir/bit_packing.cc.o
     [exec] [ 19%] Building CXX object util/CMakeFiles/kenlm_util.dir/ersatz_progress.cc.o
     [exec] [ 20%] Building CXX object util/CMakeFiles/kenlm_util.dir/exception.cc.o
     [exec] [ 21%] Building CXX object util/CMakeFiles/kenlm_util.dir/file.cc.o
     [exec] [ 23%] Building CXX object util/CMakeFiles/kenlm_util.dir/file_piece.cc.o
     [exec] [ 24%] Building CXX object util/CMakeFiles/kenlm_util.dir/float_to_string.cc.o
     [exec] [ 25%] Building CXX object util/CMakeFiles/kenlm_util.dir/integer_to_string.cc.o
     [exec] [ 26%] Building CXX object util/CMakeFiles/kenlm_util.dir/mmap.cc.o
     [exec] [ 28%] Building CXX object util/CMakeFiles/kenlm_util.dir/murmur_hash.cc.o
     [exec] [ 29%] Building CXX object util/CMakeFiles/kenlm_util.dir/parallel_read.cc.o
     [exec] [ 30%] Building CXX object util/CMakeFiles/kenlm_util.dir/pool.cc.o
     [exec] [ 32%] Building CXX object util/CMakeFiles/kenlm_util.dir/read_compressed.cc.o
     [exec] [ 33%] Building CXX object util/CMakeFiles/kenlm_util.dir/scoped.cc.o
     [exec] [ 34%] Building CXX object util/CMakeFiles/kenlm_util.dir/string_piece.cc.o
     [exec] [ 35%] Building CXX object util/CMakeFiles/kenlm_util.dir/usage.cc.o
     [exec] [ 35%] Built target kenlm_util
     [exec] Scanning dependencies of target bit_packing_test
     [exec] [ 37%] Building CXX object util/CMakeFiles/bit_packing_test.dir/bit_packing_test.cc.o
     [exec] Linking CXX executable ../bin/bit_packing_test
     [exec] util/CMakeFiles/bit_packing_test.dir/build.make:145: recipe for target 'bin/bit_packing_test' failed
     [exec] CMakeFiles/Makefile2:964: recipe for target 'util/CMakeFiles/bit_packing_test.dir/all' failed
     [exec] Makefile:126: recipe for target 'all' failed
     [exec] CMakeFiles/kenlm_util.dir/read_compressed.cc.o: In function `util::(anonymous namespace)::StreamCompressed<util::(anonymous namespace)::GZip>::~StreamCompressed()':
     [exec] read_compressed.cc:(.text+0x219): undefined reference to `inflateEnd'
     [exec] CMakeFiles/kenlm_util.dir/read_compressed.cc.o: In function `util::(anonymous namespace)::StreamCompressed<util::(anonymous namespace)::GZip>::~StreamCompressed()':
     [exec] read_compressed.cc:(.text+0x359): undefined reference to `inflateEnd'
     [exec] CMakeFiles/kenlm_util.dir/read_compressed.cc.o: In function `util::(anonymous namespace)::ReadFactory(int, unsigned long&, void const*, unsigned long, bool)':
     [exec] read_compressed.cc:(.text+0x931): undefined reference to `inflateInit2_'
     [exec] CMakeFiles/kenlm_util.dir/read_compressed.cc.o: In function `util::(anonymous namespace)::StreamCompressed<util::(anonymous namespace)::GZip>::Read(void*, unsigned long, util::ReadCompressed&)':
     [exec] read_compressed.cc:(.text+0xc5f): undefined reference to `inflate'
     [exec] collect2: error: ld returned 1 exit status
     [exec] make[2]: *** [bin/bit_packing_test] Error 1
     [exec] make[1]: *** [util/CMakeFiles/bit_packing_test.dir/all] Error 2
     [exec] make: *** [all] Error 2
     [exec] cp: cannot stat ‘bin/query’: No such file or directory
     [exec] cp: cannot stat ‘bin/lmplz’: No such file or directory
     [exec] cp: cannot stat ‘bin/build_binary’: No such file or directory
     [exec] g++: error: lm/CMakeFiles/kenlm.dir/*.o: No such file or directory
     [exec] Result: 1

Could you help me figure out what the problem is?

Regards
Sidhant

**Comment by mjpost** [comment]
I was getting this same error for a while, but then it went away with the recent update to cmake.

Two suggestions:

1. When was the last time you did a "git pull"? There were some recent updates that fixed this for me (on OS X), so make sure you have those

2. If the problem persists, try [cloning KenLM directly](github.com:kpu/kenlm), and compiling it the same way (see [this comment](https://github.com/kpu/kenlm/issues/45#issuecomment-146745044)).

Let me know what happens.

**Comment by sidhantsetia** [comment]
I tried compiling KenLM separately and it worked without any problems. The build was 100%.
After this do I again need to build Joshua or can I directly go and use Joshua?

**Comment by mjpost** [comment]
You should run "ant java" to compile the Joshua code, and should then be good to go.

**Comment by sidhantsetia** [comment]
Thanks a lot for the help Matt.
